// Generated by tools/build_week3_data.py — do not edit by hand.
const WEEK3_DATA = {
 "week": 3,
 "sigma": 25.4,
 "generatedAt": "Sep 22, 2026 \u00b7 12:03 AM ET",
 "matchups": [
  {
   "marquee": false,
   "home": "Advaith",
   "homeTeam": "First Indians",
   "homeRecord": "1-0",
   "away": "Nihar",
   "awayTeam": "Spider-Jan: Brand New Day",
   "awayRecord": "1-0",
   "homeProj": 116.16,
   "awayProj": 131.52,
   "homeWin": 27.3,
   "awayWin": 72.7,
   "seriesLine": "Nihar leads Advaith 5\u20130 (Reg. 5\u20130; Post. 0\u20130)",
   "seriesCls": "away",
   "badge": "LINEUP WATCH",
   "meetTag": "TWO MEETINGS THIS SEASON",
   "oneLiner": "Someone leaves 2\u20130. Nihar brings the current edge, led by Robinson and Prescott; Advaith answers with Justin Jefferson at 14.57.",
   "homeAvatar": "https://sleepercdn.com/avatars/thumbs/8824e5fb6de83f13b4db8736389eeecf",
   "awayAvatar": "https://sleepercdn.com/avatars/thumbs/5808fda7d6bbad03d9c4d86ad09858de",
   "heroes": [
    {
     "id": "6794",
     "name": "Justin Jefferson",
     "team": "MIN"
    },
    {
     "id": "7588",
     "name": "Javonte Williams",
     "team": "DAL"
    },
    {
     "id": "8167",
     "name": "Christian Watson",
     "team": "GB"
    },
    {
     "id": "9509",
     "name": "Bijan Robinson",
     "team": "ATL"
    },
    {
     "id": "3294",
     "name": "Dak Prescott",
     "team": "DAL"
    },
    {
     "id": "8144",
     "name": "Chris Olave",
     "team": "NO"
    }
   ],
   "swingHome": [
    {
     "pts": 13.67,
     "n": 1
    },
    {
     "pts": 57.64,
     "n": 7
    },
    {
     "pts": 36.72,
     "n": 3
    },
    {
     "pts": 8.13,
     "n": 1
    },
    {
     "pts": 0.0,
     "n": 0
    }
   ],
   "swingAway": [
    {
     "pts": 37.26,
     "n": 3
    },
    {
     "pts": 12.0,
     "n": 1
    },
    {
     "pts": 56.21,
     "n": 5
    },
    {
     "pts": 26.05,
     "n": 3
    },
    {
     "pts": 0.0,
     "n": 0
    }
   ],
   "windows": [
    "THU",
    "SUN EARLY",
    "SUN PM",
    "SUN NIGHT",
    "MON"
   ],
   "h2h": [
    {
     "season": "2022",
     "wk": 8,
     "bracket": "Regular",
     "homePts": 129.66,
     "awayPts": 138.74,
     "winner": "Nihar",
     "margin": 9.08
    },
    {
     "season": "2023",
     "wk": 1,
     "bracket": "Regular",
     "homePts": 89.06,
     "awayPts": 151.44,
     "winner": "Nihar",
     "margin": 62.38
    },
    {
     "season": "2023",
     "wk": 12,
     "bracket": "Regular",
     "homePts": 85.76,
     "awayPts": 125.14,
     "winner": "Nihar",
     "margin": 39.38
    },
    {
     "season": "2024",
     "wk": 7,
     "bracket": "Regular",
     "homePts": 90.44,
     "awayPts": 143.3,
     "winner": "Nihar",
     "margin": 52.86
    },
    {
     "season": "2025",
     "wk": 10,
     "bracket": "Regular",
     "homePts": 120.82,
     "awayPts": 151.12,
     "winner": "Nihar",
     "margin": 30.3
    }
   ],
   "homeBullets": [
    "Justin Jefferson, Javonte Williams and Christian Watson combine for 42.41 projected points \u2014 Advaith's core of this lineup.",
    "Tykee Smith projects 3.1 points ahead of Quentin Lake at DB \u2014 the biggest single-slot edge in this matchup.",
    "Advaith keeps 1 starter alive into the late windows \u2014 the final answer comes after Nihar's lineup finishes."
   ],
   "awayBullets": [
    "Bijan Robinson, Dak Prescott and Chris Olave combine for 49.28 projected points \u2014 Nihar's core of this lineup.",
    "Dak Prescott projects 16.68 points ahead of Jayden Daniels at QB \u2014 the biggest single-slot edge in this matchup.",
    "Advaith lists Jayden Daniels (OUT) in the supplied lineup. An absence there changes the math before kickoff."
   ],
   "homeLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Jayden Daniels",
     "team": "WAS",
     "opp": "BYE",
     "proj": 0,
     "injury": "OUT",
     "window": "SUN EARLY",
     "id": "11566"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Javonte Williams",
     "team": "DAL",
     "opp": "BAL",
     "proj": 14.17,
     "injury": "",
     "window": "SUN PM",
     "id": "7588"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Bhayshul Tuten",
     "team": "JAX",
     "opp": "NE",
     "proj": 11.04,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12490"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Justin Jefferson",
     "team": "MIN",
     "opp": "TB",
     "proj": 14.57,
     "injury": "",
     "window": "SUN PM",
     "id": "6794"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Christian Watson",
     "team": "GB",
     "opp": "ATL",
     "proj": 13.67,
     "injury": "",
     "window": "THU",
     "id": "8167"
    },
    {
     "slot": "TE",
     "at": false,
     "name": "Isaiah Likely",
     "team": "NYG",
     "opp": "TEN",
     "proj": 8.41,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8131"
    },
    {
     "slot": "FLEX",
     "at": true,
     "name": "Tee Higgins",
     "team": "CIN",
     "opp": "PIT",
     "proj": 12.43,
     "injury": "",
     "window": "SUN EARLY",
     "id": "6801"
    },
    {
     "slot": "K",
     "at": true,
     "name": "Evan McPherson",
     "team": "CIN",
     "opp": "PIT",
     "proj": 8.21,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7839"
    },
    {
     "slot": "DL",
     "at": true,
     "name": "Tuli Tuipulotu",
     "team": "LAC",
     "opp": "BUF",
     "proj": 8.51,
     "injury": "",
     "window": "SUN EARLY",
     "id": "10898"
    },
    {
     "slot": "LB",
     "at": false,
     "name": "Carson Schwesinger",
     "team": "CLE",
     "opp": "CAR",
     "proj": 9.04,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12578"
    },
    {
     "slot": "DB",
     "at": false,
     "name": "Tykee Smith",
     "team": "TB",
     "opp": "MIN",
     "proj": 7.98,
     "injury": "",
     "window": "SUN PM",
     "id": "11705"
    },
    {
     "slot": "IDP_FLEX",
     "at": true,
     "name": "Byron Young",
     "team": "LAR",
     "opp": "DEN",
     "proj": 8.13,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "10917"
    }
   ],
   "awayLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Dak Prescott",
     "team": "DAL",
     "opp": "BAL",
     "proj": 16.68,
     "injury": "",
     "window": "SUN PM",
     "id": "3294"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Bijan Robinson",
     "team": "ATL",
     "opp": "GB",
     "proj": 18.4,
     "injury": "",
     "window": "THU",
     "id": "9509"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Kyren Williams",
     "team": "LAR",
     "opp": "DEN",
     "proj": 12.78,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "8150"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Garrett Wilson",
     "team": "NYJ",
     "opp": "DET",
     "proj": 12.0,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8146"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Chris Olave",
     "team": "NO",
     "opp": "LV",
     "proj": 14.2,
     "injury": "",
     "window": "SUN PM",
     "id": "8144"
    },
    {
     "slot": "TE",
     "at": true,
     "name": "Kyle Pitts",
     "team": "ATL",
     "opp": "GB",
     "proj": 7.71,
     "injury": "",
     "window": "THU",
     "id": "7553"
    },
    {
     "slot": "FLEX",
     "at": true,
     "name": "Drake London",
     "team": "ATL",
     "opp": "GB",
     "proj": 11.15,
     "injury": "",
     "window": "THU",
     "id": "8112"
    },
    {
     "slot": "K",
     "at": false,
     "name": "Brandon Aubrey",
     "team": "DAL",
     "opp": "BAL",
     "proj": 9.85,
     "injury": "",
     "window": "SUN PM",
     "id": "11533"
    },
    {
     "slot": "DL",
     "at": false,
     "name": "Nik Bonitto",
     "team": "DEN",
     "opp": "LAR",
     "proj": 8.39,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "8280"
    },
    {
     "slot": "LB",
     "at": false,
     "name": "Fred Warner",
     "team": "SF",
     "opp": "ARI",
     "proj": 8.8,
     "injury": "",
     "window": "SUN PM",
     "id": "5041"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Quentin Lake",
     "team": "LAR",
     "opp": "DEN",
     "proj": 4.88,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "8330"
    },
    {
     "slot": "IDP_FLEX",
     "at": true,
     "name": "Blake Cashman",
     "team": "MIN",
     "opp": "TB",
     "proj": 6.68,
     "injury": "",
     "window": "SUN PM",
     "id": "6217"
    }
   ]
  },
  {
   "marquee": false,
   "home": "Dev",
   "homeTeam": "Develeper",
   "homeRecord": "0-1",
   "away": "Alan",
   "awayTeam": "Best Not Miss",
   "awayRecord": "1-0",
   "homeProj": 123.9,
   "awayProj": 154.26,
   "homeWin": 11.6,
   "awayWin": 88.4,
   "seriesLine": "Alan leads Dev 3\u20132 (Reg. 3\u20132; Post. 0\u20130)",
   "seriesCls": "away",
   "badge": "LINEUP WATCH",
   "meetTag": "TWO MEETINGS THIS SEASON",
   "oneLiner": "Alan leads 3\u20132 all-time. Alan brings the current edge, led by Goff and Henry; Dev answers with Brock Purdy at 20.88.",
   "homeAvatar": "https://sleepercdn.com/avatars/thumbs/bcd2b370afd6f81e8fe910a9ecd39210",
   "awayAvatar": "https://sleepercdn.com/avatars/thumbs/9be923b391e89fd671e501f4695c5c00",
   "heroes": [
    {
     "id": "8183",
     "name": "Brock Purdy",
     "team": "SF"
    },
    {
     "id": "9493",
     "name": "Puka Nacua",
     "team": "LAR"
    },
    {
     "id": "9226",
     "name": "De'Von Achane",
     "team": "MIA"
    },
    {
     "id": "3163",
     "name": "Jared Goff",
     "team": "DET"
    },
    {
     "id": "3198",
     "name": "Derrick Henry",
     "team": "BAL"
    },
    {
     "id": "8151",
     "name": "Kenneth Walker",
     "team": "KC"
    }
   ],
   "swingHome": [
    {
     "pts": 6.28,
     "n": 2
    },
    {
     "pts": 81.21,
     "n": 8
    },
    {
     "pts": 20.88,
     "n": 1
    },
    {
     "pts": 15.53,
     "n": 1
    },
    {
     "pts": 0.0,
     "n": 0
    }
   ],
   "swingAway": [
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 93.53,
     "n": 7
    },
    {
     "pts": 49.17,
     "n": 4
    },
    {
     "pts": 11.56,
     "n": 1
    },
    {
     "pts": 0.0,
     "n": 0
    }
   ],
   "windows": [
    "THU",
    "SUN EARLY",
    "SUN PM",
    "SUN NIGHT",
    "MON"
   ],
   "h2h": [
    {
     "season": "2022",
     "wk": 2,
     "bracket": "Regular",
     "homePts": 139.6,
     "awayPts": 109.2,
     "winner": "Dev",
     "margin": 30.4
    },
    {
     "season": "2022",
     "wk": 13,
     "bracket": "Regular",
     "homePts": 73.94,
     "awayPts": 88.64,
     "winner": "Alan",
     "margin": 14.7
    },
    {
     "season": "2023",
     "wk": 5,
     "bracket": "Regular",
     "homePts": 142.76,
     "awayPts": 151.58,
     "winner": "Alan",
     "margin": 8.82
    },
    {
     "season": "2024",
     "wk": 11,
     "bracket": "Regular",
     "homePts": 139.06,
     "awayPts": 135.94,
     "winner": "Dev",
     "margin": 3.12
    },
    {
     "season": "2025",
     "wk": 11,
     "bracket": "Regular",
     "homePts": 128.04,
     "awayPts": 172.46,
     "winner": "Alan",
     "margin": 44.42
    }
   ],
   "homeBullets": [
    "Brock Purdy, Puka Nacua and De'Von Achane combine for 51.32 projected points \u2014 Dev's core of this lineup.",
    "Ka'imi Fairbairn projects 1.09 points ahead of Chase McLaughlin at K \u2014 the biggest single-slot edge in this matchup.",
    "Dev keeps 1 starter alive into the late windows \u2014 the final answer comes after Alan's lineup finishes."
   ],
   "awayBullets": [
    "Jared Goff, Derrick Henry and Kenneth Walker combine for 55.57 projected points \u2014 Alan's core of this lineup.",
    "Jaylen Waddle projects 11.56 points ahead of Jayden Reed at WR \u2014 the biggest single-slot edge in this matchup.",
    "Dev lists Puka Nacua (OUT) in the supplied lineup. An absence there changes the math before kickoff."
   ],
   "homeLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Brock Purdy",
     "team": "SF",
     "opp": "ARI",
     "proj": 20.88,
     "injury": "",
     "window": "SUN PM",
     "id": "8183"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "De'Von Achane",
     "team": "MIA",
     "opp": "KC",
     "proj": 14.91,
     "injury": "",
     "window": "SUN EARLY",
     "id": "9226"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Chuba Hubbard",
     "team": "CAR",
     "opp": "CLE",
     "proj": 12.71,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7594"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Puka Nacua",
     "team": "LAR",
     "opp": "DEN",
     "proj": 15.53,
     "injury": "OUT",
     "window": "SUN NIGHT",
     "id": "9493"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Jayden Reed",
     "team": "GB",
     "opp": "ATL",
     "proj": 0,
     "injury": "OUT",
     "window": "THU",
     "id": "10222"
    },
    {
     "slot": "TE",
     "at": true,
     "name": "Darren Waller",
     "team": "CAR",
     "opp": "CLE",
     "proj": 6.82,
     "injury": "",
     "window": "SUN EARLY",
     "id": "2505"
    },
    {
     "slot": "FLEX",
     "at": false,
     "name": "Quinshon Judkins",
     "team": "CLE",
     "opp": "CAR",
     "proj": 10.99,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12512"
    },
    {
     "slot": "K",
     "at": true,
     "name": "Ka'imi Fairbairn",
     "team": "HOU",
     "opp": "IND",
     "proj": 9.61,
     "injury": "",
     "window": "SUN EARLY",
     "id": "3451"
    },
    {
     "slot": "DL",
     "at": true,
     "name": "Jeffery Simmons",
     "team": "TEN",
     "opp": "NYG",
     "proj": 7.23,
     "injury": "",
     "window": "SUN EARLY",
     "id": "6125"
    },
    {
     "slot": "LB",
     "at": true,
     "name": "Nick Bolton",
     "team": "KC",
     "opp": "MIA",
     "proj": 10.39,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7648"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Jessie Bates",
     "team": "ATL",
     "opp": "GB",
     "proj": 6.28,
     "injury": "",
     "window": "THU",
     "id": "5017"
    },
    {
     "slot": "IDP_FLEX",
     "at": false,
     "name": "Foyesade Oluokun",
     "team": "JAX",
     "opp": "NE",
     "proj": 8.55,
     "injury": "",
     "window": "SUN EARLY",
     "id": "5332"
    }
   ],
   "awayLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Jared Goff",
     "team": "DET",
     "opp": "NYJ",
     "proj": 20.12,
     "injury": "",
     "window": "SUN EARLY",
     "id": "3163"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "James Cook",
     "team": "BUF",
     "opp": "LAC",
     "proj": 15.09,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8138"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Kenneth Walker",
     "team": "KC",
     "opp": "MIA",
     "proj": 16.89,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8151"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Ja'Marr Chase",
     "team": "CIN",
     "opp": "PIT",
     "proj": 15.0,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7564"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Jaylen Waddle",
     "team": "DEN",
     "opp": "LAR",
     "proj": 11.56,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "7526"
    },
    {
     "slot": "TE",
     "at": true,
     "name": "Trey McBride",
     "team": "ARI",
     "opp": "SF",
     "proj": 13.74,
     "injury": "",
     "window": "SUN PM",
     "id": "8130"
    },
    {
     "slot": "FLEX",
     "at": true,
     "name": "Derrick Henry",
     "team": "BAL",
     "opp": "DAL",
     "proj": 18.56,
     "injury": "",
     "window": "SUN PM",
     "id": "3198"
    },
    {
     "slot": "K",
     "at": false,
     "name": "Chase McLaughlin",
     "team": "TB",
     "opp": "MIN",
     "proj": 8.52,
     "injury": "",
     "window": "SUN PM",
     "id": "6650"
    },
    {
     "slot": "DL",
     "at": false,
     "name": "T.J. Watt",
     "team": "PIT",
     "opp": "CIN",
     "proj": 8.62,
     "injury": "",
     "window": "SUN EARLY",
     "id": "4070"
    },
    {
     "slot": "LB",
     "at": false,
     "name": "Jack Campbell",
     "team": "DET",
     "opp": "NYJ",
     "proj": 9.77,
     "injury": "",
     "window": "SUN EARLY",
     "id": "10880"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Kyle Hamilton",
     "team": "BAL",
     "opp": "DAL",
     "proj": 8.35,
     "injury": "",
     "window": "SUN PM",
     "id": "8339"
    },
    {
     "slot": "IDP_FLEX",
     "at": false,
     "name": "Jordyn Brooks",
     "team": "MIA",
     "opp": "KC",
     "proj": 8.04,
     "injury": "",
     "window": "SUN EARLY",
     "id": "6949"
    }
   ]
  },
  {
   "marquee": false,
   "home": "Varun",
   "homeTeam": "Every kiss begins wth Zay",
   "homeRecord": "0-1",
   "away": "Manas",
   "awayTeam": "Concepts of a Team",
   "awayRecord": "1-0",
   "homeProj": 128.67,
   "awayProj": 128.97,
   "homeWin": 49.5,
   "awayWin": 50.5,
   "seriesLine": "Manas leads Varun 4\u20130 (Reg. 4\u20130; Post. 0\u20130)",
   "seriesCls": "away",
   "badge": "RAZOR THIN",
   "meetTag": "TWO MEETINGS THIS SEASON",
   "oneLiner": "Manas has never lost this series. Manas brings the current edge, led by Smith-Njigba and Hurts; Varun answers with Patrick Mahomes at 21.49.",
   "homeAvatar": "https://sleepercdn.com/avatars/thumbs/82aec8e811b839b8ec25d7b458afd57b",
   "awayAvatar": "https://sleepercdn.com/avatars/thumbs/8fcf0e0e6a75e96a591d2a4a4a400f41",
   "heroes": [
    {
     "id": "4046",
     "name": "Patrick Mahomes",
     "team": "KC"
    },
    {
     "id": "8155",
     "name": "Breece Hall",
     "team": "NYJ"
    },
    {
     "id": "8137",
     "name": "George Pickens",
     "team": "DAL"
    },
    {
     "id": "9488",
     "name": "Jaxon Smith-Njigba",
     "team": "SEA"
    },
    {
     "id": "6904",
     "name": "Jalen Hurts",
     "team": "PHI"
    },
    {
     "id": "9224",
     "name": "Chase Brown",
     "team": "CIN"
    }
   ],
   "swingHome": [
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 82.41,
     "n": 7
    },
    {
     "pts": 39.36,
     "n": 4
    },
    {
     "pts": 6.9,
     "n": 1
    },
    {
     "pts": 0.0,
     "n": 0
    }
   ],
   "swingAway": [
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 81.5,
     "n": 8
    },
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 7.97,
     "n": 1
    },
    {
     "pts": 39.5,
     "n": 3
    }
   ],
   "windows": [
    "THU",
    "SUN EARLY",
    "SUN PM",
    "SUN NIGHT",
    "MON"
   ],
   "h2h": [
    {
     "season": "2022",
     "wk": 4,
     "bracket": "Regular",
     "homePts": 127.08,
     "awayPts": 134.56,
     "winner": "Manas",
     "margin": 7.48
    },
    {
     "season": "2023",
     "wk": 5,
     "bracket": "Regular",
     "homePts": 134.32,
     "awayPts": 154.02,
     "winner": "Manas",
     "margin": 19.7
    },
    {
     "season": "2024",
     "wk": 9,
     "bracket": "Regular",
     "homePts": 123.14,
     "awayPts": 141.8,
     "winner": "Manas",
     "margin": 18.66
    },
    {
     "season": "2025",
     "wk": 11,
     "bracket": "Regular",
     "homePts": 133.54,
     "awayPts": 134.9,
     "winner": "Manas",
     "margin": 1.36
    }
   ],
   "homeBullets": [
    "Patrick Mahomes, Breece Hall and George Pickens combine for 47.37 projected points \u2014 Varun's core of this lineup.",
    "Nakobe Dean projects 4.93 points ahead of Anthony Hill at IDP_FLEX \u2014 the biggest single-slot edge in this matchup.",
    "Manas lists Nick Cross (Q) in the supplied lineup. An absence there changes the math before kickoff."
   ],
   "awayBullets": [
    "Jaxon Smith-Njigba, Jalen Hurts and Chase Brown combine for 51.93 projected points \u2014 Manas's core of this lineup.",
    "Jaxon Smith-Njigba projects 7.32 points ahead of George Pickens at WR \u2014 the biggest single-slot edge in this matchup.",
    "Manas keeps 4 starters alive into the late windows \u2014 the final answer comes after Varun's lineup finishes."
   ],
   "homeLineup": [
    {
     "slot": "QB",
     "at": true,
     "name": "Patrick Mahomes",
     "team": "KC",
     "opp": "MIA",
     "proj": 21.49,
     "injury": "",
     "window": "SUN EARLY",
     "id": "4046"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Breece Hall",
     "team": "NYJ",
     "opp": "DET",
     "proj": 14.13,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8155"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Rhamondre Stevenson",
     "team": "NE",
     "opp": "JAX",
     "proj": 9.7,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7611"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "George Pickens",
     "team": "DAL",
     "opp": "BAL",
     "proj": 11.75,
     "injury": "",
     "window": "SUN PM",
     "id": "8137"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "DK Metcalf",
     "team": "PIT",
     "opp": "CIN",
     "proj": 9.01,
     "injury": "",
     "window": "SUN EARLY",
     "id": "5846"
    },
    {
     "slot": "TE",
     "at": false,
     "name": "Dalton Kincaid",
     "team": "BUF",
     "opp": "LAC",
     "proj": 10.36,
     "injury": "",
     "window": "SUN EARLY",
     "id": "10236"
    },
    {
     "slot": "FLEX",
     "at": true,
     "name": "Travis Kelce",
     "team": "KC",
     "opp": "MIA",
     "proj": 10.61,
     "injury": "",
     "window": "SUN EARLY",
     "id": "1466"
    },
    {
     "slot": "K",
     "at": true,
     "name": "Tyler Loop",
     "team": "BAL",
     "opp": "DAL",
     "proj": 9.57,
     "injury": "",
     "window": "SUN PM",
     "id": "12711"
    },
    {
     "slot": "DL",
     "at": true,
     "name": "George Karlaftis",
     "team": "KC",
     "opp": "MIA",
     "proj": 7.11,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8385"
    },
    {
     "slot": "LB",
     "at": true,
     "name": "Roquan Smith",
     "team": "BAL",
     "opp": "DAL",
     "proj": 8.98,
     "injury": "",
     "window": "SUN PM",
     "id": "4960"
    },
    {
     "slot": "DB",
     "at": false,
     "name": "Brandon Jones",
     "team": "DEN",
     "opp": "LAR",
     "proj": 6.9,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "6911"
    },
    {
     "slot": "IDP_FLEX",
     "at": true,
     "name": "Nakobe Dean",
     "team": "LV",
     "opp": "NO",
     "proj": 9.06,
     "injury": "",
     "window": "SUN PM",
     "id": "8267"
    }
   ],
   "awayLineup": [
    {
     "slot": "QB",
     "at": true,
     "name": "Jalen Hurts",
     "team": "PHI",
     "opp": "CHI",
     "proj": 18.78,
     "injury": "",
     "window": "MON",
     "id": "6904"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Chase Brown",
     "team": "CIN",
     "opp": "PIT",
     "proj": 14.08,
     "injury": "",
     "window": "SUN EARLY",
     "id": "9224"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "D'Andre Swift",
     "team": "CHI",
     "opp": "PHI",
     "proj": 11.81,
     "injury": "",
     "window": "MON",
     "id": "6790"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Jaxon Smith-Njigba",
     "team": "SEA",
     "opp": "WAS",
     "proj": 19.07,
     "injury": "",
     "window": "SUN EARLY",
     "id": "9488"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Jalen Coker",
     "team": "CAR",
     "opp": "CLE",
     "proj": 12.68,
     "injury": "",
     "window": "SUN EARLY",
     "id": "11646"
    },
    {
     "slot": "TE",
     "at": false,
     "name": "Pat Freiermuth",
     "team": "PIT",
     "opp": "CIN",
     "proj": 6.75,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7600"
    },
    {
     "slot": "FLEX",
     "at": true,
     "name": "Davante Adams",
     "team": "LAR",
     "opp": "DEN",
     "proj": 7.97,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "2133"
    },
    {
     "slot": "K",
     "at": true,
     "name": "Jason Myers",
     "team": "SEA",
     "opp": "WAS",
     "proj": 9.14,
     "injury": "",
     "window": "SUN EARLY",
     "id": "2747"
    },
    {
     "slot": "DL",
     "at": true,
     "name": "Will Anderson",
     "team": "HOU",
     "opp": "IND",
     "proj": 8.53,
     "injury": "",
     "window": "SUN EARLY",
     "id": "10892"
    },
    {
     "slot": "LB",
     "at": true,
     "name": "Zack Baun",
     "team": "PHI",
     "opp": "CHI",
     "proj": 8.91,
     "injury": "",
     "window": "MON",
     "id": "6815"
    },
    {
     "slot": "DB",
     "at": false,
     "name": "Nick Cross",
     "team": "WAS",
     "opp": "SEA",
     "proj": 7.12,
     "injury": "Q",
     "window": "SUN EARLY",
     "id": "8392"
    },
    {
     "slot": "IDP_FLEX",
     "at": true,
     "name": "Anthony Hill",
     "team": "TEN",
     "opp": "NYG",
     "proj": 4.13,
     "injury": "",
     "window": "SUN EARLY",
     "id": "13365"
    }
   ]
  },
  {
   "marquee": false,
   "home": "Achal",
   "homeTeam": "Its your bye week ",
   "homeRecord": "0-1",
   "away": "Vaibhav",
   "awayTeam": "The Padawans",
   "awayRecord": "1-0",
   "homeProj": 95.71,
   "awayProj": 136.3,
   "homeWin": 5.5,
   "awayWin": 94.5,
   "seriesLine": "Achal leads Vaibhav 3\u20132 (Reg. 2\u20132; Post. 1\u20130)",
   "seriesCls": "home",
   "badge": "BLOWOUT POTENTIAL",
   "meetTag": "TWO MEETINGS THIS SEASON",
   "oneLiner": "Achal leads 3\u20132 all-time. Vaibhav brings the current edge, led by Herbert and St. Brown; Achal answers with Malik Willis at 17.51.",
   "homeAvatar": "https://sleepercdn.com/avatars/thumbs/e7af4deab0289b4f5505646424895246",
   "awayAvatar": "https://sleepercdn.com/avatars/thumbs/0cab8164a4f51e3aedb9729b4221bffe",
   "heroes": [
    {
     "id": "8161",
     "name": "Malik Willis",
     "team": "MIA"
    },
    {
     "id": "11635",
     "name": "Ladd McConkey",
     "team": "LAC"
    },
    {
     "id": "5967",
     "name": "Tony Pollard",
     "team": "TEN"
    },
    {
     "id": "6797",
     "name": "Justin Herbert",
     "team": "LAC"
    },
    {
     "id": "7547",
     "name": "Amon-Ra St. Brown",
     "team": "DET"
    },
    {
     "id": "12507",
     "name": "Omarion Hampton",
     "team": "LAC"
    }
   ],
   "swingHome": [
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 89.56,
     "n": 10
    },
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 6.15,
     "n": 2
    }
   ],
   "swingAway": [
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 99.31,
     "n": 8
    },
    {
     "pts": 20.47,
     "n": 2
    },
    {
     "pts": 16.52,
     "n": 2
    },
    {
     "pts": 0.0,
     "n": 0
    }
   ],
   "windows": [
    "THU",
    "SUN EARLY",
    "SUN PM",
    "SUN NIGHT",
    "MON"
   ],
   "h2h": [
    {
     "season": "2022",
     "wk": 5,
     "bracket": "Regular",
     "homePts": 132.08,
     "awayPts": 120.02,
     "winner": "Achal",
     "margin": 12.06
    },
    {
     "season": "2023",
     "wk": 7,
     "bracket": "Regular",
     "homePts": 141.26,
     "awayPts": 91.86,
     "winner": "Achal",
     "margin": 49.4
    },
    {
     "season": "2024",
     "wk": 9,
     "bracket": "Regular",
     "homePts": 115.48,
     "awayPts": 140.88,
     "winner": "Vaibhav",
     "margin": 25.4
    },
    {
     "season": "2024",
     "wk": 17,
     "bracket": "Postseason",
     "homePts": 159.82,
     "awayPts": 118.48,
     "winner": "Achal",
     "margin": 41.34
    },
    {
     "season": "2025",
     "wk": 4,
     "bracket": "Regular",
     "homePts": 81.82,
     "awayPts": 195.12,
     "winner": "Vaibhav",
     "margin": 113.3
    }
   ],
   "homeBullets": [
    "Malik Willis, Ladd McConkey and Tony Pollard combine for 39.54 projected points \u2014 Achal's core of this lineup.",
    "Demetrius Knight projects 1.13 points ahead of Ernest Jones at LB \u2014 the biggest single-slot edge in this matchup.",
    "Achal keeps 2 starters alive into the late windows \u2014 the final answer comes after Vaibhav's lineup finishes."
   ],
   "awayBullets": [
    "Justin Herbert, Amon-Ra St. Brown and Omarion Hampton combine for 47.43 projected points \u2014 Vaibhav's core of this lineup.",
    "Aidan Hutchinson projects 10.86 points ahead of Jalyx Hunt at DL \u2014 the biggest single-slot edge in this matchup.",
    "Vaibhav keeps 2 starters alive into the late windows \u2014 the final answer comes after Achal's lineup finishes."
   ],
   "homeLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Malik Willis",
     "team": "MIA",
     "opp": "KC",
     "proj": 17.51,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8161"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Chris Rodriguez",
     "team": "JAX",
     "opp": "NE",
     "proj": 5.66,
     "injury": "",
     "window": "SUN EARLY",
     "id": "10219"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Tony Pollard",
     "team": "TEN",
     "opp": "NYG",
     "proj": 10.57,
     "injury": "",
     "window": "SUN EARLY",
     "id": "5967"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Ladd McConkey",
     "team": "LAC",
     "opp": "BUF",
     "proj": 11.46,
     "injury": "",
     "window": "SUN EARLY",
     "id": "11635"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Wan'Dale Robinson",
     "team": "TEN",
     "opp": "NYG",
     "proj": 7.44,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8126"
    },
    {
     "slot": "TE",
     "at": false,
     "name": "Greg Dulcich",
     "team": "MIA",
     "opp": "KC",
     "proj": 4.73,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8172"
    },
    {
     "slot": "FLEX",
     "at": false,
     "name": "Kyle Monangai",
     "team": "CHI",
     "opp": "PHI",
     "proj": 6.15,
     "injury": "",
     "window": "MON",
     "id": "12534"
    },
    {
     "slot": "K",
     "at": false,
     "name": "Tyler Bass",
     "team": "BUF",
     "opp": "LAC",
     "proj": 9.53,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7042"
    },
    {
     "slot": "DL",
     "at": true,
     "name": "Jalyx Hunt",
     "team": "PHI",
     "opp": "BYE",
     "proj": 0,
     "injury": "",
     "window": "MON",
     "id": "11703"
    },
    {
     "slot": "LB",
     "at": true,
     "name": "Demetrius Knight",
     "team": "CIN",
     "opp": "PIT",
     "proj": 8.45,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12617"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Marcus Jones",
     "team": "NE",
     "opp": "JAX",
     "proj": 6.46,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8359"
    },
    {
     "slot": "IDP_FLEX",
     "at": true,
     "name": "Mike Jackson",
     "team": "CAR",
     "opp": "CLE",
     "proj": 7.75,
     "injury": "",
     "window": "SUN EARLY",
     "id": "6025"
    }
   ],
   "awayLineup": [
    {
     "slot": "QB",
     "at": true,
     "name": "Justin Herbert",
     "team": "LAC",
     "opp": "BUF",
     "proj": 16.79,
     "injury": "",
     "window": "SUN EARLY",
     "id": "6797"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Ashton Jeanty",
     "team": "LV",
     "opp": "NO",
     "proj": 12.47,
     "injury": "",
     "window": "SUN PM",
     "id": "12527"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Omarion Hampton",
     "team": "LAC",
     "opp": "BUF",
     "proj": 14.01,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12507"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Amon-Ra St. Brown",
     "team": "DET",
     "opp": "NYJ",
     "proj": 16.63,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7547"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Tetairoa McMillan",
     "team": "CAR",
     "opp": "CLE",
     "proj": 12.32,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12526"
    },
    {
     "slot": "TE",
     "at": false,
     "name": "Tyler Warren",
     "team": "IND",
     "opp": "HOU",
     "proj": 8.14,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12518"
    },
    {
     "slot": "FLEX",
     "at": false,
     "name": "Parker Washington",
     "team": "JAX",
     "opp": "NE",
     "proj": 13.24,
     "injury": "",
     "window": "SUN EARLY",
     "id": "9487"
    },
    {
     "slot": "K",
     "at": true,
     "name": "Harrison Mevis",
     "team": "LAR",
     "opp": "DEN",
     "proj": 8.97,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "12015"
    },
    {
     "slot": "DL",
     "at": false,
     "name": "Aidan Hutchinson",
     "team": "DET",
     "opp": "NYJ",
     "proj": 10.86,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8289"
    },
    {
     "slot": "LB",
     "at": true,
     "name": "Ernest Jones",
     "team": "SEA",
     "opp": "WAS",
     "proj": 7.32,
     "injury": "",
     "window": "SUN EARLY",
     "id": "7672"
    },
    {
     "slot": "DB",
     "at": false,
     "name": "Talanoa Hufanga",
     "team": "DEN",
     "opp": "LAR",
     "proj": 7.55,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "7811"
    },
    {
     "slot": "IDP_FLEX",
     "at": true,
     "name": "Dallas Turner",
     "team": "MIN",
     "opp": "TB",
     "proj": 8.0,
     "injury": "",
     "window": "SUN PM",
     "id": "11667"
    }
   ]
  },
  {
   "marquee": false,
   "home": "Taylor",
   "homeTeam": "Fannin the Flames",
   "homeRecord": "0-1",
   "away": "Dhiraj",
   "awayTeam": "Love thy Nabers",
   "awayRecord": "0-1",
   "homeProj": 126.94,
   "awayProj": 121.82,
   "homeWin": 58.0,
   "awayWin": 42.0,
   "seriesLine": "Taylor leads Dhiraj 6\u20131 (Reg. 5\u20131; Post. 1\u20130)",
   "seriesCls": "home",
   "badge": "",
   "meetTag": "TWO MEETINGS THIS SEASON",
   "oneLiner": "Someone gets their first win. Taylor brings the current edge, led by Allen and Barkley; Dhiraj answers with Baker Mayfield at 14.78.",
   "homeAvatar": "https://sleepercdn.com/avatars/thumbs/13b3abfb116819fffaf9cedfb5734d61",
   "awayAvatar": "https://sleepercdn.com/avatars/thumbs/8eb8f8bf999945d523f2c4033f70473e",
   "heroes": [
    {
     "id": "4984",
     "name": "Josh Allen",
     "team": "BUF"
    },
    {
     "id": "4866",
     "name": "Saquon Barkley",
     "team": "PHI"
    },
    {
     "id": "6786",
     "name": "CeeDee Lamb",
     "team": "DAL"
    },
    {
     "id": "4892",
     "name": "Baker Mayfield",
     "team": "TB"
    },
    {
     "id": "7525",
     "name": "DeVonta Smith",
     "team": "PHI"
    },
    {
     "id": "13287",
     "name": "Jeremiyah Love",
     "team": "ARI"
    }
   ],
   "swingHome": [
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 59.93,
     "n": 6
    },
    {
     "pts": 43.54,
     "n": 4
    },
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 23.47,
     "n": 2
    }
   ],
   "swingAway": [
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 54.57,
     "n": 6
    },
    {
     "pts": 53.67,
     "n": 5
    },
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 13.58,
     "n": 1
    }
   ],
   "windows": [
    "THU",
    "SUN EARLY",
    "SUN PM",
    "SUN NIGHT",
    "MON"
   ],
   "h2h": [
    {
     "season": "2022",
     "wk": 11,
     "bracket": "Regular",
     "homePts": 126.98,
     "awayPts": 156.04,
     "winner": "Dhiraj",
     "margin": 29.06
    },
    {
     "season": "2023",
     "wk": 3,
     "bracket": "Regular",
     "homePts": 121.82,
     "awayPts": 121.26,
     "winner": "Taylor",
     "margin": 0.56
    },
    {
     "season": "2023",
     "wk": 14,
     "bracket": "Regular",
     "homePts": 152.72,
     "awayPts": 86.84,
     "winner": "Taylor",
     "margin": 65.88
    },
    {
     "season": "2024",
     "wk": 2,
     "bracket": "Regular",
     "homePts": 142.06,
     "awayPts": 134.62,
     "winner": "Taylor",
     "margin": 7.44
    },
    {
     "season": "2024",
     "wk": 13,
     "bracket": "Regular",
     "homePts": 177.42,
     "awayPts": 140.92,
     "winner": "Taylor",
     "margin": 36.5
    },
    {
     "season": "2024",
     "wk": 15,
     "bracket": "Postseason",
     "homePts": 184.98,
     "awayPts": 97.9,
     "winner": "Taylor",
     "margin": 87.08
    },
    {
     "season": "2025",
     "wk": 4,
     "bracket": "Regular",
     "homePts": 179.76,
     "awayPts": 95.88,
     "winner": "Taylor",
     "margin": 83.88
    }
   ],
   "homeBullets": [
    "Josh Allen, Saquon Barkley and CeeDee Lamb combine for 49.25 projected points \u2014 Taylor's core of this lineup.",
    "Josh Allen projects 6.03 points ahead of Baker Mayfield at QB \u2014 the biggest single-slot edge in this matchup.",
    "Dhiraj lists Malik Nabers (Q) in the supplied lineup. An absence there changes the math before kickoff."
   ],
   "awayBullets": [
    "Baker Mayfield, DeVonta Smith and Jeremiyah Love combine for 41.65 projected points \u2014 Dhiraj's core of this lineup.",
    "Jacory Croskey-Merritt projects 4.59 points ahead of Rachaad White at RB \u2014 the biggest single-slot edge in this matchup.",
    "Taylor lists Saquon Barkley (Q) in the supplied lineup. An absence there changes the math before kickoff."
   ],
   "homeLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Josh Allen",
     "team": "BUF",
     "opp": "LAC",
     "proj": 20.81,
     "injury": "",
     "window": "SUN EARLY",
     "id": "4984"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Saquon Barkley",
     "team": "PHI",
     "opp": "CHI",
     "proj": 14.95,
     "injury": "Q",
     "window": "MON",
     "id": "4866"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Rachaad White",
     "team": "WAS",
     "opp": "SEA",
     "proj": 5.44,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8136"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "CeeDee Lamb",
     "team": "DAL",
     "opp": "BAL",
     "proj": 13.49,
     "injury": "",
     "window": "SUN PM",
     "id": "6786"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "Rashee Rice",
     "team": "KC",
     "opp": "MIA",
     "proj": 11.2,
     "injury": "",
     "window": "SUN EARLY",
     "id": "10229"
    },
    {
     "slot": "TE",
     "at": true,
     "name": "Mark Andrews",
     "team": "BAL",
     "opp": "DAL",
     "proj": 9.46,
     "injury": "",
     "window": "SUN PM",
     "id": "5012"
    },
    {
     "slot": "FLEX",
     "at": false,
     "name": "Mike Evans",
     "team": "SF",
     "opp": "ARI",
     "proj": 11.73,
     "injury": "Q",
     "window": "SUN PM",
     "id": "2216"
    },
    {
     "slot": "K",
     "at": true,
     "name": "Cameron Dicker",
     "team": "LAC",
     "opp": "BUF",
     "proj": 8.71,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8259"
    },
    {
     "slot": "DL",
     "at": false,
     "name": "Josh Hines-Allen",
     "team": "JAX",
     "opp": "NE",
     "proj": 7.43,
     "injury": "",
     "window": "SUN EARLY",
     "id": "5840"
    },
    {
     "slot": "LB",
     "at": true,
     "name": "Azeez Al-Shaair",
     "team": "HOU",
     "opp": "IND",
     "proj": 6.34,
     "injury": "",
     "window": "SUN EARLY",
     "id": "6485"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Cooper DeJean",
     "team": "PHI",
     "opp": "CHI",
     "proj": 8.52,
     "injury": "",
     "window": "MON",
     "id": "11678"
    },
    {
     "slot": "IDP_FLEX",
     "at": true,
     "name": "Maxx Crosby",
     "team": "LV",
     "opp": "NO",
     "proj": 8.86,
     "injury": "",
     "window": "SUN PM",
     "id": "5991"
    }
   ],
   "awayLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Baker Mayfield",
     "team": "TB",
     "opp": "MIN",
     "proj": 14.78,
     "injury": "",
     "window": "SUN PM",
     "id": "4892"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Jeremiyah Love",
     "team": "ARI",
     "opp": "SF",
     "proj": 13.29,
     "injury": "",
     "window": "SUN PM",
     "id": "13287"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Jacory Croskey-Merritt",
     "team": "WAS",
     "opp": "SEA",
     "proj": 10.03,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12533"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Malik Nabers",
     "team": "NYG",
     "opp": "TEN",
     "proj": 11.96,
     "injury": "Q",
     "window": "SUN EARLY",
     "id": "11632"
    },
    {
     "slot": "WR",
     "at": true,
     "name": "DeVonta Smith",
     "team": "PHI",
     "opp": "CHI",
     "proj": 13.58,
     "injury": "",
     "window": "MON",
     "id": "7525"
    },
    {
     "slot": "TE",
     "at": false,
     "name": "Brenton Strange",
     "team": "JAX",
     "opp": "NE",
     "proj": 7.6,
     "injury": "",
     "window": "SUN EARLY",
     "id": "9480"
    },
    {
     "slot": "FLEX",
     "at": true,
     "name": "Aaron Jones",
     "team": "MIN",
     "opp": "TB",
     "proj": 11.47,
     "injury": "Q",
     "window": "SUN PM",
     "id": "4199"
    },
    {
     "slot": "K",
     "at": false,
     "name": "Chris Boswell",
     "team": "PIT",
     "opp": "CIN",
     "proj": 8.48,
     "injury": "",
     "window": "SUN EARLY",
     "id": "1945"
    },
    {
     "slot": "DL",
     "at": false,
     "name": "Nick Bosa",
     "team": "SF",
     "opp": "ARI",
     "proj": 7.5,
     "injury": "",
     "window": "SUN PM",
     "id": "5816"
    },
    {
     "slot": "LB",
     "at": true,
     "name": "Devin Lloyd",
     "team": "CAR",
     "opp": "CLE",
     "proj": 9.8,
     "injury": "",
     "window": "SUN EARLY",
     "id": "8329"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Kevin Byard",
     "team": "NE",
     "opp": "JAX",
     "proj": 6.7,
     "injury": "",
     "window": "SUN EARLY",
     "id": "3233"
    },
    {
     "slot": "IDP_FLEX",
     "at": false,
     "name": "Josiah Trotter",
     "team": "TB",
     "opp": "MIN",
     "proj": 6.63,
     "injury": "",
     "window": "SUN PM",
     "id": "13379"
    }
   ]
  },
  {
   "marquee": false,
   "home": "Soham",
   "homeTeam": "The RB shelter",
   "homeRecord": "0-1",
   "away": "Shiamak",
   "awayTeam": "Super Lamario Bros",
   "awayRecord": "1-0",
   "homeProj": 119.49,
   "awayProj": 139.02,
   "homeWin": 22.1,
   "awayWin": 77.9,
   "seriesLine": "Shiamak leads Soham 5\u20132 (Reg. 5\u20131; Post. 0\u20131)",
   "seriesCls": "away",
   "badge": "LINEUP WATCH",
   "meetTag": "TWO MEETINGS THIS SEASON",
   "oneLiner": "Shiamak leads 5\u20132 all-time. Shiamak brings the current edge, led by Jackson and Gibbs; Soham answers with Jaxson Dart at 19.01.",
   "homeAvatar": "https://sleepercdn.com/avatars/thumbs/ab5692c5f3357dbd2533d4e22db11ba9",
   "awayAvatar": "https://sleepercdn.com/avatars/thumbs/8eb8f8bf999945d523f2c4033f70473e",
   "heroes": [
    {
     "id": "12508",
     "name": "Jaxson Dart",
     "team": "NYG"
    },
    {
     "id": "12481",
     "name": "Cam Skattebo",
     "team": "NYG"
    },
    {
     "id": "13286",
     "name": "Jadarian Price",
     "team": "SEA"
    },
    {
     "id": "4881",
     "name": "Lamar Jackson",
     "team": "BAL"
    },
    {
     "id": "9221",
     "name": "Jahmyr Gibbs",
     "team": "DET"
    },
    {
     "id": "6813",
     "name": "Jonathan Taylor",
     "team": "IND"
    }
   ],
   "swingHome": [
    {
     "pts": 18.4,
     "n": 2
    },
    {
     "pts": 75.14,
     "n": 7
    },
    {
     "pts": 16.95,
     "n": 2
    },
    {
     "pts": 9.0,
     "n": 1
    },
    {
     "pts": 0.0,
     "n": 0
    }
   ],
   "swingAway": [
    {
     "pts": 8.64,
     "n": 1
    },
    {
     "pts": 57.51,
     "n": 4
    },
    {
     "pts": 72.87,
     "n": 6
    },
    {
     "pts": 0.0,
     "n": 0
    },
    {
     "pts": 0.0,
     "n": 1
    }
   ],
   "windows": [
    "THU",
    "SUN EARLY",
    "SUN PM",
    "SUN NIGHT",
    "MON"
   ],
   "h2h": [
    {
     "season": "2022",
     "wk": 2,
     "bracket": "Regular",
     "homePts": 98.26,
     "awayPts": 137.76,
     "winner": "Shiamak",
     "margin": 39.5
    },
    {
     "season": "2022",
     "wk": 13,
     "bracket": "Regular",
     "homePts": 129.94,
     "awayPts": 98.76,
     "winner": "Soham",
     "margin": 31.18
    },
    {
     "season": "2022",
     "wk": 15,
     "bracket": "Postseason",
     "homePts": 144.1,
     "awayPts": 92.66,
     "winner": "Soham",
     "margin": 51.44
    },
    {
     "season": "2023",
     "wk": 3,
     "bracket": "Regular",
     "homePts": 100.58,
     "awayPts": 149.94,
     "winner": "Shiamak",
     "margin": 49.36
    },
    {
     "season": "2023",
     "wk": 14,
     "bracket": "Regular",
     "homePts": 108.0,
     "awayPts": 115.84,
     "winner": "Shiamak",
     "margin": 7.84
    },
    {
     "season": "2024",
     "wk": 8,
     "bracket": "Regular",
     "homePts": 135.86,
     "awayPts": 151.16,
     "winner": "Shiamak",
     "margin": 15.3
    },
    {
     "season": "2025",
     "wk": 4,
     "bracket": "Regular",
     "homePts": 93.9,
     "awayPts": 150.98,
     "winner": "Shiamak",
     "margin": 57.08
    }
   ],
   "homeBullets": [
    "Jaxson Dart, Cam Skattebo and Jadarian Price combine for 43.65 projected points \u2014 Soham's core of this lineup.",
    "Tucker Kraft projects 9.64 points ahead of Dallas Goedert at TE \u2014 the biggest single-slot edge in this matchup.",
    "Shiamak lists Dallas Goedert (Q) in the supplied lineup. An absence there changes the math before kickoff."
   ],
   "awayBullets": [
    "Lamar Jackson, Jahmyr Gibbs and Jonathan Taylor combine for 63.08 projected points \u2014 Shiamak's core of this lineup.",
    "Christian McCaffrey projects 8.81 points ahead of MarShawn Lloyd at FLEX \u2014 the biggest single-slot edge in this matchup.",
    "Soham lists Jaxson Dart (OUT) in the supplied lineup. An absence there changes the math before kickoff."
   ],
   "homeLineup": [
    {
     "slot": "QB",
     "at": false,
     "name": "Jaxson Dart",
     "team": "NYG",
     "opp": "TEN",
     "proj": 19.01,
     "injury": "OUT",
     "window": "SUN EARLY",
     "id": "12508"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Cam Skattebo",
     "team": "NYG",
     "opp": "TEN",
     "proj": 13.99,
     "injury": "",
     "window": "SUN EARLY",
     "id": "12481"
    },
    {
     "slot": "RB",
     "at": true,
     "name": "Jadarian Price",
     "team": "SEA",
     "opp": "WAS",
     "proj": 10.65,
     "injury": "Q",
     "window": "SUN EARLY",
     "id": "13286"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Courtland Sutton",
     "team": "DEN",
     "opp": "LAR",
     "proj": 9.0,
     "injury": "",
     "window": "SUN NIGHT",
     "id": "5045"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Devaughn Vele",
     "team": "NO",
     "opp": "LV",
     "proj": 7.77,
     "injury": "",
     "window": "SUN PM",
     "id": "11834"
    },
    {
     "slot": "TE",
     "at": false,
     "name": "Tucker Kraft",
     "team": "GB",
     "opp": "ATL",
     "proj": 9.64,
     "injury": "",
     "window": "THU",
     "id": "9484"
    },
    {
     "slot": "FLEX",
     "at": false,
     "name": "MarShawn Lloyd",
     "team": "GB",
     "opp": "ATL",
     "proj": 8.76,
     "injury": "",
     "window": "THU",
     "id": "11581"
    },
    {
     "slot": "K",
     "at": false,
     "name": "Cam Little",
     "team": "JAX",
     "opp": "NE",
     "proj": 9.28,
     "injury": "",
     "window": "SUN EARLY",
     "id": "11786"
    },
    {
     "slot": "DL",
     "at": true,
     "name": "Andrew Van Ginkel",
     "team": "MIN",
     "opp": "TB",
     "proj": 9.18,
     "injury": "",
     "window": "SUN PM",
     "id": "6183"
    },
    {
     "slot": "LB",
     "at": false,
     "name": "Sonny Styles",
     "team": "WAS",
     "opp": "SEA",
     "proj": 7.66,
     "injury": "",
     "window": "SUN EARLY",
     "id": "13375"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Julian Love",
     "team": "SEA",
     "opp": "WAS",
     "proj": 7.6,
     "injury": "",
     "window": "SUN EARLY",
     "id": "5876"
    },
    {
     "slot": "IDP_FLEX",
     "at": false,
     "name": "Nick Herbig",
     "team": "PIT",
     "opp": "CIN",
     "proj": 6.95,
     "injury": "",
     "window": "SUN EARLY",
     "id": "10940"
    }
   ],
   "awayLineup": [
    {
     "slot": "QB",
     "at": true,
     "name": "Lamar Jackson",
     "team": "BAL",
     "opp": "DAL",
     "proj": 24.04,
     "injury": "",
     "window": "SUN PM",
     "id": "4881"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Jahmyr Gibbs",
     "team": "DET",
     "opp": "NYJ",
     "proj": 20.25,
     "injury": "",
     "window": "SUN EARLY",
     "id": "9221"
    },
    {
     "slot": "RB",
     "at": false,
     "name": "Jonathan Taylor",
     "team": "IND",
     "opp": "HOU",
     "proj": 18.79,
     "injury": "",
     "window": "SUN EARLY",
     "id": "6813"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Emeka Egbuka",
     "team": "TB",
     "opp": "MIN",
     "proj": 8.21,
     "injury": "",
     "window": "SUN PM",
     "id": "12514"
    },
    {
     "slot": "WR",
     "at": false,
     "name": "Terry McLaurin",
     "team": "WAS",
     "opp": "SEA",
     "proj": 8.59,
     "injury": "",
     "window": "SUN EARLY",
     "id": "5927"
    },
    {
     "slot": "TE",
     "at": true,
     "name": "Dallas Goedert",
     "team": "PHI",
     "opp": "BYE",
     "proj": 0,
     "injury": "Q",
     "window": "MON",
     "id": "5022"
    },
    {
     "slot": "FLEX",
     "at": false,
     "name": "Christian McCaffrey",
     "team": "SF",
     "opp": "ARI",
     "proj": 17.57,
     "injury": "",
     "window": "SUN PM",
     "id": "4034"
    },
    {
     "slot": "K",
     "at": true,
     "name": "Matt Gay",
     "team": "LV",
     "opp": "NO",
     "proj": 8.68,
     "injury": "",
     "window": "SUN PM",
     "id": "6083"
    },
    {
     "slot": "DL",
     "at": false,
     "name": "Brian Burns",
     "team": "NYG",
     "opp": "TEN",
     "proj": 9.88,
     "injury": "Q",
     "window": "SUN EARLY",
     "id": "5862"
    },
    {
     "slot": "LB",
     "at": false,
     "name": "Edgerrin Cooper",
     "team": "GB",
     "opp": "ATL",
     "proj": 8.64,
     "injury": "Q",
     "window": "THU",
     "id": "11687"
    },
    {
     "slot": "DB",
     "at": true,
     "name": "Budda Baker",
     "team": "ARI",
     "opp": "SF",
     "proj": 6.92,
     "injury": "",
     "window": "SUN PM",
     "id": "4081"
    },
    {
     "slot": "IDP_FLEX",
     "at": false,
     "name": "Caleb Downs",
     "team": "DAL",
     "opp": "BAL",
     "proj": 7.45,
     "injury": "",
     "window": "SUN PM",
     "id": "13376"
    }
   ]
  }
 ]
};
